### ISSUE TITLE
PHP error in version 4.0.1

### ISSUE THREAD

**Issue by martin-git-kristensen** [tieupmedia/HwtTypo3HwtAddress#10]
My backend and frontend in typo3 11.5.35 get crashed with the following error:
PHP Warning: Undefined array key "hwt_address" in /var/www/html/vendor/tieupmedia/hwt_address/ext_localconf.php line 28

**Comment by martin-git-kristensen** [comment]
of course I ment version 0.4.1

**Comment by tieupmedia** [comment]
Thank you for reporting! A bugfix release will be available soon.

But I think, your TYPO3 error settings are not optimal / like in the install tool suggested. This error produces a log entry by default, but shouldn't crash the backend.
