### ISSUE TITLE
Integration of composer

### ISSUE THREAD

**Issue by dpfahlbusch** [tieupmedia/HwtTypo3HwtAddress#2]
Maybe integrate the possibility to install the extension via composer. :)

**Comment by tieupmedia** [comment]
Thanks for the hint! Meanwhile, some more TYPO3 programmers may use composer.

I created a packagist repository for it and added the composer.json. Feel free to test and give feedback!

**Comment by tieupmedia** [comment]
I added missing autoload informations today and it worked fine on my test host. So for now, I think it's done. Feel free to open an new issue, if something is missing or a bug occurs.
