### ISSUE TITLE
Typo3 9 SQL Error when saving new Address record

### ISSUE THREAD

**Issue by kahnesaaron** [tieupmedia/HwtTypo3HwtAddress#4]
I get an error when i try to save a new address record. I am only creating company records therefore i want to set the birthday.

2: SQL error: 'Incorrect integer value: '' for column 'birthday' at row 1' (tx_hwtaddress_domain_model_address:NEW5cc30665156ed413492145)

![error](https://user-images.githubusercontent.com/29655317/56810776-66e0a880-6837-11e9-9b9b-48d10354c2c6.jpg)

**Comment by tieupmedia** [comment]
First thanks for your report!

I took a look and tried to reproduce this, but i couldn't until. I tried to create records with:
- set a birthday - ok
- leave the field empty - ok
- disable the field via TCEMAIN - ok

You DON'T want to set the birthday, cause you are creating company records, or am I wrong?

Which TYPO3, PHP and MySQL versions to you use?

Best regards!

**Comment by saschaluebeck** [comment]
I know the problem was because of SQL strict mode by Laragon. After changing to "sql-mode = "NO_ENGINE_SUBSTITUTION" the error did not appear again.

**Comment by tieupmedia** [comment]
Thanks a lot for this input! It gives me something to go on. Further solution options are given by http://www.typo3forum.net/discussion/50799/neue-seite-anlegen

Somewhere else I read that the core of 7.x was not compatible to the MySQL strict mode. Did you test it with a newer major version?

**Comment by saschaluebeck** [comment]
The Typo3 for this project is a 9.5.6.

**Comment by tieupmedia** [comment]
@kahnesaaron @saschaluebeck can you please check, if the branch [bug-sql-strict-birthday](/tieupmedia/HwtTypo3HwtAddress/tree/bug-sql-strict-birthday) resolves this in strict mode?

**Comment by saschaluebeck** [comment]
I think that should work. I will test it next week an reply here.

**Comment by tieupmedia** [comment]
That would be great, thanks for your contribution!

**Comment by kahnesaaron** [comment]
@tieupmedia  have tested your new branch with the sql strict mode bug fix and its working like intended.
Thank you very much!

**Comment by tieupmedia** [comment]
@kahnesaaron thank you much! It will be merged into the next release. I think it will be available in the next two weeks.

**Comment by tieupmedia** [comment]
See fe76d12

**Comment by tieupmedia** [comment]
Resolved with release 0.2.2
