### ISSUE TITLE
Typo 9.5.6 - PHP Warning at listAction with no addressStorage

### ISSUE THREAD

**Issue by saschaluebeck** [tieupmedia/HwtTypo3HwtAddress#5]
When not setting a addressStoragePages to use single Adresses instead, an php Error appears:

PHP Warning: count(): Parameter must be an array or an object that implements Countable in ***\typo3conf\ext\hwt_address\Classes\Controller\AddressController.php line 102.

Suggestions: change line 102 to

`if ((!$addressRecords || (count($addressRecords)==0)) && $this->settings['addressRecords']) {`

**Comment by tieupmedia** [comment]
Hey Sascha,

thank you much, for reporting!

It's just fixed in the current master, after @amtee discovered this, too. The next TER release including the fix will be available in the upcoming days.

Best regards!

**Comment by saschaluebeck** [comment]
Ah, I see. All right!
Thanks for this pretty nice extension! Good work :)

**Comment by tieupmedia** [comment]
Thank you for your commendation!
If you have any suggestion for further improvements or new features, please let me know.

**Comment by tieupmedia** [comment]
See 1dd45d7

**Comment by tieupmedia** [comment]
Resolved with release 0.2.1
